@startuml
       actor 图书管理员
       participant "登录系统"
       participant "图书记录"
       participant "借阅记录"
       actor "借阅者"

       图书管理员 -> 登录系统: 1:登陆账号
       activate 图书管理员
       activate 登录系统
       登录系统-->图书管理员: 2: 返回登录成功信息
       deactivate 登录系统
       deactivate 图书管理员

       图书管理员->借阅者::   3:获取借阅者信息
       activate 图书管理员
       activate 借阅者
       deactivate 借阅者

       图书管理员->借阅记录 ::       4:获取逾期时间
       activate 借阅记录
       借阅记录->借阅记录:: 5:根据规则获取罚款金额
       deactivate 图书管理员
       deactivate 借阅记录

       借阅者-->图书管理员 :: 6:缴纳相应罚款
       activate 图书管理员
       activate 借阅者
       deactivate 图书管理员
       deactivate 借阅者
 @enduml